version: '3.8'
services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - micro_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro_net

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro_net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      discovery-service:
        condition: service_healthy
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
