server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    
  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/api_gateway
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  # Spring Cloud Gateway Configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,routes
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.example.apigateway: DEBUG
